package org.takanolab.actionlog;

public class Stringrs {
	public static String[] modelNamesL = {
		"-amphibia-",
		"Canadian Toad",
		"Western Toad",
		"Boreal Chorus Frog",
		"Northern Leopard Frog",
		"Wood Frog",
		"Columbia Spotted Frog",
		"Long-Toed Salamander",
		"Tiger Salamander",
		"-Bird-",
		"Blue-winged Teal",
		"Cinnamon Teal",
		"Northern Shoveler",
		"Tundra Swan",
		"Green-winged Teal",
		"Canvasback",
		"Redhead",
		"Ring-necked Duck",
		"Greater Scaup",
		"Lesser Scaup",
		"Harlequin Duck",
		"Canada Goose",
		"Northern Pintail",
		"Snow Goose",
		"Ross's Goose",
		"Wood Duck",
		"Gadwall",
		"Eurasian Wigeon",
		"American Wigeon",
		"Mallard",
		"broad winged hawk",
		"Bald eagle",
		"Grus americana",
		"virginia rail",
		"Baltimore oriole",
		"Steller's Jay",
		"Black Backed Woodpecker",
		"Spruce Grouse",
		"Great horned owl",
		"-fish-",
		"Lake Sturgeon",
		"White sturgeon",
		"Trout-perch",
		"Western Longnose Sucker",
		"Longnose Sucker",
		"White Sucker",
		"Mountain Sucker",
		"Pearl Dace",
		"Banff Longnose Dace",
		"Fathead Minnow",
		"Finescale Dace",
		"Northern Redbelly Dace",
		"Lake Chub",
		"Goldfish ",
		"Longnose Dace",
		"Green Swordtail",
		"Guppy ",
		"Sailfin Molly",
		"Western Mosquitofish",
		"Northern Pike",
		"Burbot",
		"Brook Stickleback",
		"Goldeye",
		"blackbass",
		"Convict Cichlid",
		"Freshwater Angelfish",
		"African Jewelfish",
		"Brilliant Blue Discus Fish",
		"Yellow Perch",
		"Sauger",
		"Walleye",
		"Greenback cutthroat trout",
		"Bull Trout",
		"Mountain Whitefish",
		"Brook Trout",
		"Grayling",
		"Mountain White Fish",
		"Arctic Char",
		"Atlantic Salmon",
		"Lake Trout",
		"Lake Whitefish",
		"Cisco",
		"Rainbow Trout",
		"Lake Whitefish",
		"Lake Trout",
		"Golden Trout",
		"Yellowstone cutthroat trout",
		"Arctic grayling",
		"Brown Trout",
		"Cutthroat Trout",
		"-insect-",
		"Leptinotarsa Decemlineata",
		"Ladybug",
		"Mountain Pine Beetle",
		"Ephemeroptera",
		"Sympetrum Danae",
		"Melanoplus Spretus",
		"-mammal-",
		"Mountain Goat",
		"Bighorn Sheep",
		"Bison",
		"Woodland Caribou",
		"Elk ",
		"Moose",
		"Coyote",
		"Gray Wolf",
		"White Wolf",
		"Red Fox",
		"Canada Lynx",
		"Cougar",
		"Least Weasel",
		"Wolverine",
		"River Otter",
		"Striped Skunk",
		"Badger ",
		"Mink",
		"Long-tailed Weasel",
		"Marten",
		"Ermine ",
		"Fisher ",
		"Grizzly Bear ",
		"Black Bear",
		"Little Brown Bat",
		"Hoary Bat",
		"Big Brown Bat",
		"Silver-haired Bat",
		"Long-eared Bat",
		"Long-legged Bat",
		"Snowshoe Hare",
		"Pika",
		"Beaver",
		"Deer Mouse",
		"Long-tailed Vole",
		"Water Vole",
		"Muskrat ",
		"Southern Red-backed Vole",
		"Heather Vole",
		"Meadow Vole",
		"Bushy-tailed Wood Rat",
		"Northern Bog Lemming",
		"Western Jumping Mouse",
		"Porcupine",
		"Columbian Ground Squirrel",
		"Yellow-pine Chipmunk",
		"Least Chipmunk",
		"Hoary Marmot",
		"Red Squirrel",
		"Northern Flying Squirrel",
		"Golden-mantled Ground Squirrel",
		"Dusky Shrew",
		"Masked Shrew",
		"Northern Water Shrew",
		"Pygmy Shrew",
		"-plant-",
		"Starflowered Solomon's Seal",
		"Large yellow lady's slipper",
		"Heart-leaved Arnica",
		"Black-eyed Susan",
		"Common Yarrow",
		"Fleabanes",
		"Common Harebell",
		"Moss Campion",
		"Moss Campion",
		"Mountain Sorrel",
		"Fringed Grass-of-Parnassus",
		"Bunchberry",
		"Bunchberry",
		"Twinflower",
		"Twinflower",
		"Sitka Valerian",
		"Single Delight",
		"Labrador Tea",
		"White-flowered Rhododendron",
		"Bearberry",
		"Heather",
		"Rock Jasmine",
		"Pretty Shooting Star",
		"Single Delight",
		"Yellow Hedysarum",
		"Northern Bedstraw",
		"Alpine Forget-Me-Not",
		"Alpine Forget-Me-Not",
		"Silky Phacelia",
		"Common Butterwort",
		"Indian Paintbrush",
		"Indian Paintbrush",
		"Alpine Speedwell",
		"Triangular-leaved ragworts grace treeline glades",
		"Glacier Lily",
		"Glacier Lily",
		"Machingun Lily",
		"Western Wood Lily",
		"Bronze Bells",
		"Prairie Crocus",
		"Mountain Fireweed",
		"Fireweed",
		"Pinus Banksiana",
		"Prairie Crocus",
		"Yellow Columbine",
		"Western Anemone",
		"Three-flowered Avens",
		"Wild Rose",
		"Wild Strawberry",
		"Shrubby Cinquefoil",
		"White Mountain Avens",
		"Stonecrop",
		"Spotted Saxifrage",
		"Purple Saxifrage",
		"Purple Saxifrage",
		"-reptillia-",
		"Rubber Boa",
		"Wandering Garter Snake",
		"Rattlesnake",
		"desert tortoise"
	};
	public static String[] modelNames = {
		"canadian_toad",
		"canadian_toad",
		"western_toad",
		"boreal_chorus_frog",
		"northern_leopard_frog",
		"wood_frog",
		"columbia_spotted_frog",
		"long_toed_salamander",
		"tiger_salamander",
		"blue_winged_teal",
		"blue_winged_teal",
		"cinnamon_teal",
		"northern_shoveler",
		"tundra_swan",
		"green_winged_teal",
		"canvasback",
		"redhead",
		"ring_necked_duck",
		"greater_scaup",
		"lesser_scaup",
		"harlequin_duck",
		"canada_goose",
		"northern_pintail",
		"snow_goose",
		"ross_s_goose",
		"wood_duck",
		"gadwall",
		"eurasian_wigeon",
		"american_wigeon",
		"mallard",
		"broad_winged_hawk",
		"bald_eagle",
		"grus_americana",
		"irginia_rail",
		"baltimore_oriole",
		"steller_s_jay",
		"black_backed_woodpecker",
		"spruce_grouse",
		"great_horned_owl",
		"lake_sturgeon",
		"lake_sturgeon",
		"white_sturgeon",
		"trout_perch",
		"western_longnose_sucker",
		"longnose_sucker",
		"white_sucker",
		"mountain_sucker",
		"pearl_dace",
		"banff_longnose_dace",
		"fathead_minnow",
		"finescale_dace",
		"northern_redbelly_dace",
		"lake_chub",
		"goldfish",
		"longnose_dace",
		"green_swordtail",
		"guppy_",
		"sailfin_molly",
		"western_mosquitofish",
		"northern_pike",
		"burbot",
		"brook_stickleback",
		"goldeye",
		"blackbass",
		"convict_cichlid",
		"freshwater_angelfish",
		"african_jewelfish",
		"brilliant_blue_discus_fish",
		"yellow_perch",
		"sauger",
		"walleye",
		"greenback_cutthroat_trout",
		"bull_trout",
		"mountain_whitefish",
		"brook_trout",
		"grayling",
		"mountain_white_fish",
		"arctic_char",
		"atlantic_salmon",
		"lake_trout",
		"lake_whitefish",
		"cisco",
		"rainbow_trout",
		"lake_whitefish",
		"lake_trout",
		"golden_trout",
		"yellowstone_cutthroat_trout",
		"arctic_grayling",
		"brown_trout",
		"cutthroat_trout",
		"leptinotarsa_decemlineata",
		"leptinotarsa_decemlineata",
		"ladybug",
		"mountain_pine_beetle",
		"ephemeroptera",
		"sympetrum_danae",
		"melanoplus_spretus",
		"mountain_goat",
		"mountain_goat",
		"bighorn_sheep",
		"bison",
		"woodland_caribou",
		"elk ",
		"moose",
		"coyote",
		"gray_wolf",
		"white_wolf",
		"red_fox",
		"canada_lynx",
		"cougar",
		"least_weasel",
		"wolverine",
		"river_otter",
		"striped_skunk",
		"badger ",
		"mink",
		"long_tailed_weasel",
		"marten",
		"ermine ",
		"fisher ",
		"grizzly_bear ",
		"black_bear",
		"little_brown_bat",
		"hoary_bat",
		"big_brown_bat",
		"silver_haired_bat",
		"long_eared_bat",
		"long_legged_bat",
		"snowshoe_hare",
		"pika",
		"beaver",
		"deer_mouse",
		"long_tailed_vole",
		"water_vole",
		"muskrat ",
		"southern_red_backed_vole",
		"heather_vole",
		"meadow_vole",
		"bushy_tailed_wood_rat",
		"northern_bog_lemming",
		"western_jumping_mouse",
		"porcupine",
		"columbian_ground_squirrel",
		"yellow_pine_chipmunk",
		"least_chipmunk",
		"hoary_marmot",
		"red_squirrel",
		"northern_flying_squirrel",
		"golden_mantled_ground_squirrel",
		"dusky_shrew",
		"masked_shrew",
		"northern_water_shrew",
		"pygmy_shrew",
		"starflowered_solomon_s_seal",
		"starflowered_solomon_s_seal",
		"large_yellow_lady_s_slipper",
		"heart_leaved_arnica",
		"black_eyed_susan",
		"common_yarrow",
		"fleabanes",
		"common_harebell",
		"moss_campion",
		"moss_campion",
		"mountain_sorrel",
		"fringed_grass_of_parnassus",
		"bunchberry",
		"bunchberry",
		"twinflower",
		"twinflower",
		"sitka_valerian",
		"single_delight",
		"labrador_tea",
		"white_flowered_rhododendron",
		"bearberry",
		"heather",
		"rock_jasmine",
		"pretty_shooting_star",
		"single_delight",
		"yellow_hedysarum",
		"northern_bedstraw",
		"alpine_forget_me_not",
		"alpine_forget_me_not",
		"silky_phacelia",
		"common_butterwort",
		"indian_paintbrush",
		"indian_paintbrush",
		"alpine_speedwell",
		"triangular_leaved_ragworts_grace_treeline_glades",
		"glacier_lily",
		"glacier_lily",
		"machingun_lily",
		"western_wood_lily",
		"bronze_bells",
		"prairie_crocus",
		"mountain_fireweed",
		"fireweed",
		"pinus_banksiana",
		"prairie_crocus",
		"yellow_columbine",
		"western_anemone",
		"three_flowered_avens",
		"wild_rose",
		"wild_strawberry",
		"shrubby_cinquefoil",
		"white_mountain_avens",
		"stonecrop",
		"spotted_saxifrage",
		"purple_saxifrage",
		"purple_saxifrage",
		"rubber_boa",
		"rubber_boa",
		"wandering_garter_snake",
		"rattlesnake",
		"desert_tortoise"
	};
}
