package org.takanolab.actionlog;

public class Stringrs {
	public static String[] modelNamesL = {
		"---Bird---",
		"Canada Goose",
		"Tundra Swan",
		"Snow Goose",
		"Ross's Goose",
		"Wood Duck",
		"Gadwall",
		"Eurasian Wigeon",
		"American Wigeon",
		"Mallard",
		"Blue-winged Teal",
		"Cinnamon Teal",
		"Northern Shoveler",
		"Northern Pintail",
		"Green-winged Teal",
		"Canvasback",
		"Redhead",
		"Ring-necked Duck",
		"Greater Scaup",
		"Lesser Scaup",
		"Harlequin Duck",
		"virginia rail",
		"broad winged hawk",
		"Great horned owl",
		"Grus americana",
		"Baltimore oriole",
		"Bald eagle",
		"Black Backed Woodpecker",
		"Spruce Grouse",
		"Steller's Jay",
		"---Mammal---",
		"Masked Shrew",
		"Dusky Shrew",
		"Northern Water Shrew",
		"Pygmy Shrew",
		"Little Brown Bat",
		"Long-eared Bat",
		"Long-legged Bat",
		"Silver-haired Bat",
		"Big Brown Bat",
		"Hoary Bat",
		"Pika",
		"Snowshoe Hare",
		"Least Chipmunk",
		"Yellow-pine Chipmunk",
		"Hoary Marmot",
		"Columbian Ground Squirrel",
		"Golden-mantled Ground Squirrel",
		"Red Squirrel",
		"Northern Flying Squirrel",
		"Beaver",
		"Deer Mouse",
		"Bushy-tailed Wood Rat",
		"Southern Red-backed Vole",
		"Heather Vole",
		"Meadow Vole",
		"Long-tailed Vole",
		"Water Vole",
		"Muskrat ",
		"Northern Bog Lemming",
		"Western Jumping Mouse",
		"Porcupine",
		"Coyote",
		"Gray Wolf",
		"Red Fox",
		"White Wolf",
		"Black Bear",
		"Grizzly Bear ",
		"Marten",
		"Fisher ",
		"Ermine ",
		"Least Weasel",
		"Long-tailed Weasel",
		"Mink",
		"Badger ",
		"Striped Skunk",
		"River Otter",
		"Wolverine",
		"Cougar",
		"Canada Lynx",
		"Elk ",
		"Moose",
		"Woodland Caribou",
		"Bighorn Sheep",
		"Mountain Goat",
		"Bison",
		"---Fish---",
		"Rainbow Trout",
		"Brown Trout",
		"Cutthroat Trout",
		"Bull Trout",
		"Mountain Whitefish",
		"Brook Trout",
		"Greenback cutthroat trout",
		"Yellowstone cutthroat trout",
		"White sturgeon",
		"Golden Trout",
		"Lake Trout",
		"Lake Whitefish",
		"Arctic grayling",
		"Lake Sturgeon",
		"Burbot",
		"Northern Pike",
		"Sauger",
		"Goldeye",
		"Yellow Perch",
		"Walleye",
		"Cisco",
		"Lake Whitefish",
		"Lake Trout",
		"Atlantic Salmon",
		"Arctic Char",
		"Goldfish ",
		"Lake Chub",
		"Northern Redbelly Dace",
		"Finescale Dace",
		"Fathead Minnow",
		"Longnose Dace",
		"Banff Longnose Dace",
		"Pearl Dace",
		"Longnose Sucker",
		"White Sucker",
		"Mountain Sucker",
		"Trout-perch",
		"Western Mosquitofish",
		"Sailfin Molly",
		"Guppy ",
		"Green Swordtail",
		"Brook Stickleback",
		"African Jewelfish",
		"Convict Cichlid",
		"Freshwater Angelfish",
		"Brilliant Blue Discus Fish",
		"blackbass",
		"Grayling",
		"Mountain White Fish",
		"Western Longnose Sucker",
		"---Insect---",
		"Mountain Pine Beetle",
		"Ephemeroptera",
		"Ladybug",
		"Leptinotarsa Decemlineata",
		"Melanoplus Spretus",
		"Sympetrum Danae",
		"---Amphibia---",
		"Wood Frog",
		"Boreal Chorus Frog",
		"Columbia Spotted Frog",
		"Northern Leopard Frog",
		"Western Toad",
		"Canadian Toad",
		"Long-Toed Salamander",
		"Tiger Salamander",
		"---Reptillia---",
		"Wandering Garter Snake",
		"Rubber Boa",
		"desert tortoise",
		"Rattlesnake",
		"---Prant---",
		"Prairie Crocus",
		"Western Wood Lily",
		"Three-flowered Avens",
		"Starflowered Solomon's Seal",
		"Black-eyed Susan",
		"Large yellow lady's slipper",
		"Common Butterwort",
		"Bunchberry",
		"Twinflower",
		"Single Delight",
		"Pretty Shooting Star",
		"Moss Campion",
		"Purple Saxifrage",
		"Glacier Lily",
		"Alpine Forget-Me-Not",
		"Bunchberry",
		"Twinflower",
		"Bronze Bells",
		"Single Delight",
		"Labrador Tea",
		"White-flowered Rhododendron",
		"Sitka Valerian",
		"Fleabanes",
		"Triangular-leaved ragworts grace treeline glades",
		"Moss Campion",
		"Purple Saxifrage",
		"Glacier Lily",
		"Alpine Speedwell",
		"Alpine Forget-Me-Not",
		"Western Anemone",
		"White Mountain Avens",
		"Mountain Sorrel",
		"Silky Phacelia",
		"Heather",
		"Wild Rose",
		"Indian Paintbrush",
		"Rock Jasmine",
		"Wild Strawberry",
		"Fireweed",
		"Shrubby Cinquefoil",
		"Yellow Columbine",
		"Heart-leaved Arnica",
		"Fringed Grass-of-Parnassus",
		"Yellow Hedysarum",
		"Common Harebell",
		"Spotted Saxifrage",
		"Stonecrop",
		"Bearberry",
		"Mountain Fireweed",
		"Common Yarrow",
		"Northern Bedstraw",
		"Indian Paintbrush",
		"Prairie Crocus",
		"Machingun Lily",
		"Pinus Banksiana"
	};
	public static String[] modelNames = {
		"canada_goose",
		"canada_goose",
		"tundra_swan",
		"snow_goose",
		"ross_s_goose",
		"wood_duck",
		"gadwall",
		"eurasian_wigeon",
		"american_wigeon",
		"mallard",
		"blue_winged_teal",
		"cinnamon_teal",
		"northern_shoveler",
		"northern_pintail",
		"green_winged_teal",
		"canvasback",
		"redhead",
		"ring_necked_duck",
		"greater_scaup",
		"lesser_scaup",
		"harlequin_duck",
		"irginia_rail",
		"broad_winged_hawk",
		"great_horned_owl",
		"grus_americana",
		"baltimore_oriole",
		"bald_eagle",
		"black_backed_woodpecker",
		"spruce_grouse",
		"steller_s_jay",
		"masked_shrew",
		"masked_shrew",
		"dusky_shrew",
		"northern_water_shrew",
		"pygmy_shrew",
		"little_brown_bat",
		"long_eared_bat",
		"long_legged_bat",
		"silver_haired_bat",
		"big_brown_bat",
		"hoary_bat",
		"pika",
		"snowshoe_hare",
		"least_chipmunk",
		"yellow_pine_chipmunk",
		"hoary_marmot",
		"columbian_ground_squirrel",
		"golden_mantled_ground_squirrel",
		"red_squirrel",
		"northern_flying_squirrel",
		"beaver",
		"deer_mouse",
		"bushy_tailed_wood_rat",
		"southern_red_backed_vole",
		"heather_vole",
		"meadow_vole",
		"long_tailed_vole",
		"water_vole",
		"muskrat ",
		"northern_bog_lemming",
		"western_jumping_mouse",
		"porcupine",
		"coyote",
		"gray_wolf",
		"red_fox",
		"white_wolf",
		"black_bear",
		"grizzly_bear ",
		"marten",
		"fisher ",
		"ermine ",
		"least_weasel",
		"long_tailed_weasel",
		"mink",
		"badger ",
		"striped_skunk",
		"river_otter",
		"wolverine",
		"cougar",
		"canada_lynx",
		"elk ",
		"moose",
		"woodland_caribou",
		"bighorn_sheep",
		"mountain_goat",
		"bison",
		"rainbow_trout",
		"rainbow_trout",
		"brown_trout",
		"cutthroat_trout",
		"bull_trout",
		"mountain_whitefish",
		"brook_trout",
		"greenback_cutthroat_trout",
		"yellowstone_cutthroat_trout",
		"white_sturgeon",
		"golden_trout",
		"lake_trout",
		"lake_whitefish",
		"arctic_grayling",
		"lake_sturgeon",
		"burbot",
		"northern_pike",
		"sauger",
		"goldeye",
		"yellow_perch",
		"walleye",
		"cisco",
		"lake_whitefish",
		"lake_trout",
		"atlantic_salmon",
		"arctic_char",
		"goldfish",
		"lake_chub",
		"northern_redbelly_dace",
		"finescale_dace",
		"fathead_minnow",
		"longnose_dace",
		"banff_longnose_dace",
		"pearl_dace",
		"longnose_sucker",
		"white_sucker",
		"mountain_sucker",
		"trout_perch",
		"western_mosquitofish",
		"sailfin_molly",
		"guppy_",
		"green_swordtail",
		"brook_stickleback",
		"african_jewelfish",
		"convict_cichlid",
		"freshwater_angelfish",
		"brilliant_blue_discus_fish",
		"blackbass",
		"grayling",
		"mountain_white_fish",
		"western_longnose_sucker",
		"mountain_pine_beetle",
		"mountain_pine_beetle",
		"ephemeroptera",
		"ladybug",
		"leptinotarsa_decemlineata",
		"melanoplus_spretus",
		"sympetrum_danae",
		"wood_frog",
		"wood_frog",
		"boreal_chorus_frog",
		"columbia_spotted_frog",
		"northern_leopard_frog",
		"western_toad",
		"canadian_toad",
		"long_toed_salamander",
		"tiger_salamander",
		"wandering_garter_snake",
		"wandering_garter_snake",
		"rubber_boa",
		"desert_tortoise",
		"rattlesnake",
		"prairie_crocus",
		"prairie_crocus",
		"western_wood_lily",
		"three_flowered_avens",
		"starflowered_solomon_s_seal",
		"black_eyed_susan",
		"large_yellow_lady_s_slipper",
		"common_butterwort",
		"bunchberry",
		"twinflower",
		"single_delight",
		"pretty_shooting_star",
		"moss_campion",
		"purple_saxifrage",
		"glacier_lily",
		"alpine_forget_me_not",
		"bunchberry",
		"twinflower",
		"bronze_bells",
		"single_delight",
		"labrador_tea",
		"white_flowered_rhododendron",
		"sitka_valerian",
		"fleabanes",
		"triangular_leaved_ragworts_grace_treeline_glades",
		"moss_campion",
		"purple_saxifrage",
		"glacier_lily",
		"alpine_speedwell",
		"alpine_forget_me_not",
		"western_anemone",
		"white_mountain_avens",
		"mountain_sorrel",
		"silky_phacelia",
		"heather",
		"wild_rose",
		"indian_paintbrush",
		"rock_jasmine",
		"wild_strawberry",
		"fireweed",
		"shrubby_cinquefoil",
		"yellow_columbine",
		"heart_leaved_arnica",
		"fringed_grass_of_parnassus",
		"yellow_hedysarum",
		"common_harebell",
		"spotted_saxifrage",
		"stonecrop",
		"bearberry",
		"mountain_fireweed",
		"common_yarrow",
		"northern_bedstraw",
		"indian_paintbrush",
		"prairie_crocus",
		"machingun_lily",
		"pinus_banksiana"
	};
}
